samples:
  D1-W-49_S14_L001_R1_001: fastq/D1-W-49_S14_L001_R1_001.fastq
  D2-A-71_S5_L004_R1_001: fastq/D2-A-71_S5_L004_R1_001.fastq
  negD1-WC-40_S2_L003_R1_001: fastq/negD1-WC-40_S2_L003_R1_001.fastq

index: "/home/resources/mm10_hisat2_index/genome"

gtf: "/home/resources/Mus_musculus.GRCm38.84.gtf"

alignment: 
  threads: 4
