# REQUIRED ARGUMENTS -

type: "paired" # single or paired

experiment: "rnaseq" # chipseq or rnaseq

threads_for_alignment: 1

index: "/Users/Aarthi/resources/mm10_hisat2_index/genome" # path to basename of HISAT2 index

multiqc_yaml: "/Users/Aarthi/resources/multiqc_config.yaml" # example file provided in NGS-Data-Charmer folder



# ONLY FOR RNASEQ -

gtf: "/Users/Aarthi/resources/Mus_musculus.GRCm38.84.gtf" # path to gtf file 



# ONLY FOR CHIPSEQ -

chr_sizes: "/home/aarthi/resources/mm10.chrom.sizes" # path to chr.sizes file (only for chipseq)

