type: "paired" # single or paired

experiment: "rnaseq" # chipseq or rnaseq

alignment: 
  threads: 4

multiqc_yaml: "/home/aarthi/resources/multiqc_config_example.yaml"

index: "/home/aarthi/resources/mm10_hisat2_index/genome"

# only for rnaseq
gtf: "/home/aarthi/resources/Mus_musculus.GRCm38.84.gtf"

# only for chipseq
chr_sizes: "/home/aarthi/resources/mm10.chrom.sizes"
sam_chr_header: "/home/aarthi/resources/header_mm10_90_chr.sam"







