type: "single" # single or paired

experiment: "chipseq" # chipseq or rnaseq

alignment: 
  threads: 4

multiqc_yaml: "/home/aarthi/resources/multiqc_config_example.yaml"

index: "/Users/Aarthi 1/Desktop/RNAseq-Charmer/mm10_hisat2_index/genome"

# only for rnaseq
gtf: "/Users/Aarthi 1/Desktop/RNAseq-Charmer/Mus_musculus.GRCm38.84.gtf"

# only for chipseq
chr_sizes: "/Users/Aarthi 1/Desktop/RNAseq-Charmer/mm10.chrom.sizes"
sam_chr_header: "/home/aarthi/resources/header_mm10_90_chr.sam"







