#required arguments

type: "paired" # single or paired

experiment: "chipseq" # chipseq or rnaseq or cutrun

threads_for_alignment: 4 # May be increased to speed up alignment

index: "/path/to/hisat_genome/mm10/genome" # path to basename of HISAT2 index

bowtie2_index: "/path/to/Bowtie2Index/genome" # path to basename of bowtie2 index

multiqc_yaml: "/path/to/Tools/NGS-Data-Charmer-COPY/multiqc_config_template.yaml" # example file provided in NGS-Data-Charmer folder

# FOR CUT&RUN AND CHIPSEQ -
chr_sizes: "/path/to/mm10/mm10_chr_len" # path to chr.sizes file (only for chipseq)

# ONLY FOR RNASEQ -
gtf: "/path/to/gencode.vM22.annotation.gtf"
count_scheme: "fraction" # fraction or count_all or count_uniq

# OUTPUT options
keep_fastq: "FALSE"  # Independent of the other "stopping point" rules; trimmed fastq files are kept.
keep_unfiltered_bam: "FALSE" # Keep the unfiltered bam file (contains unmapped reads and duplicates)
to_tdf: "TRUE" # Produce TDF files
to_bed: "TRUE" # Produce bed files
to_bw: "TRUE" # Produce bigwig of reads from main chromsomes
to_multiqc: "TRUE" # Run entire pipeline and create multiqc report
