name: ngs_data_charmer

channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - graphviz=2.38.0
  - python=3.5.1
  - snakemake=3.11.0
  - pyyaml=3.11
  - hisat2=2.1.0
  - perl=5.22.0.1
  - htseq=0.9.1
  - pysam=0.13.0
  - pandas=0.21.0
  - igvtools=2.3.93
  - bedtools=2.27.1

